[project]
name = "redis-lock-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.5",
    "loguru>=0.7.2",
    "redis==5.0.4",
]

[tool.uv]
dev-dependencies = [
    "aiohttp>=3.11.0",
]

